### PR TITLE
Feature/accessibility

### PR DESCRIPTION
**Pull request by chinatsu**
the big change here is `.usePdfUaAccessbility(true)`, which makes a fair bit of PDF/UA-requirements produce warnings. thanks a lot to @tidnav for bringing this stuff up! we're definitely interested in making it easy to produce well defined PDF documents that achieve good accessibility. this hasn't really been a priority up until now.

ideally, i'd like those warnings to be thrown as errors so the accessibility-requirements actually need to be fixed to produce PDFs, but we haven't really looked too hard into this.

everyone who upgrades to v2 should update all of their templates with requirements such as 
```html
    <meta name="subject" content="Dokumentemne"/>
    <meta name="author" content="pdfgen"/>
    <meta name="description" content="Test template"/>
```
in the head. `alt`-props in `` tags, `title`-props in `<a>` tags, ideally avoid `position: absolute;` in css, and maybe worst of all: logical reading order of the HTML.

the accessibility work is yet to be finalized, e.g. we don't quite know if we're solving everything with this, so i want to version it as a release candidate. we'll increment the release candidate number until we have a good idea of what's needed, including well defined documentation on how to achieve proper UA.

### CODE REVIEW

**Comment by chinatsu** [comment]
unfortunately none of the UA-issues produce errors, so i can only make it so that the logs show nothing about UA-issues. :)

**Comment by MikAoJk** [comment]
Looks very good only 2 things that we should have a look at now:

1. The linter is angry localy, on this file GeneratePdfApi.kt on line 99: ` [no-blank-line-before-rbrace] Unexpected blank line(s) before "}"`
2. We should also update the README.md, with the new version: 2.0.0-rc1

All in all, its a very good PR :smiley:

**Comment by chinatsu** [comment]
1. We didn't touch this file on this branch, so I guess it was introduced earlier. Either way I'll fix it.
2. I'm not sure if I want to announce 2.0.0-rc1 in the readme just yet, at least not before we've actually documented what's new and what's required from people using pdfgen. This is kind of a preliminary PR before actually releasing 2.0.0, so to speak. We could also consider making a new kind of workflow for these kinds of release candidates, although I think it's fairly rare that we introduce "breaking" changes like this.

**Comment by chinatsu** [comment]
I changed my mind, and added a little blurb about v2 in the readme :relieved:

**Review by MikAoJk — APPROVED** [review]

**Pull request merged**
