### PR TITLE
Upgrade to ktor 2.1.0

### PR DESCRIPTION
**Pull request by MikAoJk**

### CODE REVIEW

**Comment by MikAoJk** [comment]
Need help on how to list on List of all routes.
Before this was done by, `feature(Routing)`

**Comment by chinatsu** [comment]
I think messageFor404 can simply be changed to something like this 
```kotlin
private fun messageFor404(templates: Map<Pair<String, String>, Template>, path: String) =
    "Unkown path '$path'. Known templates:\n" + templates.map { (app, _) -> 
        "/api/v1/genpdf/%s/%s".format(app.first, app.second)
    }.joinToString("\n")
```

this page should only be encountered during development (unless someone's misconfigured their paths), so I think it's fine that we're a little bit sloppy and don't strictly check if the path has been registered properly, nor do we *have* to specify whether the path is GET or POST tbh. i would like to expect that people know, but if it becomes a problem somehow we can sort it out later by passing `disablePdfGet` in and using that to determine whether paths have GET as well as the usual POST

with this approach we can also throw away `apiRoutes` and `allRoutes`.

also, bump the version to 1.5.1 in `build.gradle.kts` and `Dockerfile` :pray:

**Comment by MikAoJk** [comment]
Nice, will fix this today😁

**Comment by MikAoJk** [comment]
@chinatsu fix is implemented

**Review by chinatsu — APPROVED** [review]

**Pull request merged**
