### PR TITLE
Update pdfgencore

### PR DESCRIPTION
**Pull request by dragutin-nav**

### CODE REVIEW

**Comment by MikAoJk** [comment]
Need this first: https://github.com/navikt/pdfgen/pull/176

**Comment by MikAoJk** [comment]
Also duplicate of: https://github.com/navikt/pdfgen/pull/177
@dragutin-nav 

Ask @madsop-nav if there are any progress

**Comment by madsop-nav** [comment]
Would certainly be happy with some help on #176

**Comment by MikAoJk** [comment]
Maybe @heyvard can help😅

**Pull request closed without merging**
